
import { KeyboardLayout, KeyConfig } from './types';

export const KEYBOARD_87_LAYOUT: KeyboardLayout = [
  // F-Row + System Keys
  [
    { code: 'Escape', label: 'Esc', width: 1.25 },
    { code: 'spacer', label: '', width: 1 },
    { code: 'F1', label: 'F1' },
    { code: 'F2', label: 'F2' },
    { code: 'F3', label: 'F3' },
    { code: 'F4', label: 'F4' },
    { code: 'spacer', label: '', width: 0.5 },
    { code: 'F5', label: 'F5' },
    { code: 'F6', label: 'F6' },
    { code: 'F7', label: 'F7' },
    { code: 'F8', label: 'F8' },
    { code: 'spacer', label: '', width: 0.5 },
    { code: 'F9', label: 'F9' },
    { code: 'F10', label: 'F10' },
    { code: 'F11', label: 'F11' },
    { code: 'F12', label: 'F12' },
    { code: 'spacer', label: '', width: 0.25 },
    { code: 'PrintScreen', label: 'PrtSc' },
    { code: 'ScrollLock', label: 'ScrLk' },
    { code: 'Pause', label: 'Pause' },
  ],
  // Number Row
  [
    { code: 'Backquote', label: '` ~' },
    { code: 'Digit1', label: '1 !' },
    { code: 'Digit2', label: '2 @' },
    { code: 'Digit3', label: '3 #' },
    { code: 'Digit4', label: '4 $' },
    { code: 'Digit5', label: '5 %' },
    { code: 'Digit6', label: '6 ^' },
    { code: 'Digit7', label: '7 &' },
    { code: 'Digit8', label: '8 *' },
    { code: 'Digit9', label: '9 (' },
    { code: 'Digit0', label: '0 )' },
    { code: 'Minus', label: '- _' },
    { code: 'Equal', label: '= +' },
    { code: 'Backspace', label: 'Back', width: 2 },
    { code: 'spacer', label: '', width: 0.25 },
    { code: 'Insert', label: 'Ins' },
    { code: 'Home', label: 'Home' },
    { code: 'PageUp', label: 'PgUp' },
  ],
  // QWERTY Row
  [
    { code: 'Tab', label: 'Tab', width: 1.5 },
    { code: 'KeyQ', label: 'Q' },
    { code: 'KeyW', label: 'W' },
    { code: 'KeyE', label: 'E' },
    { code: 'KeyR', label: 'R' },
    { code: 'KeyT', label: 'T' },
    { code: 'KeyY', label: 'Y' },
    { code: 'KeyU', label: 'U' },
    { code: 'KeyI', label: 'I' },
    { code: 'KeyO', label: 'O' },
    { code: 'KeyP', label: 'P' },
    { code: 'BracketLeft', label: '[ {' },
    { code: 'BracketRight', label: '] }' },
    { code: 'Backslash', label: '\\ |', width: 1.5 },
    { code: 'spacer', label: '', width: 0.25 },
    { code: 'Delete', label: 'Del' },
    { code: 'End', label: 'End' },
    { code: 'PageDown', label: 'PgDn' },
  ],
  // ASDF Row
  [
    { code: 'CapsLock', label: 'Caps', width: 1.75 },
    { code: 'KeyA', label: 'A' },
    { code: 'KeyS', label: 'S' },
    { code: 'KeyD', label: 'D' },
    { code: 'KeyF', label: 'F' },
    { code: 'KeyG', label: 'G' },
    { code: 'KeyH', label: 'H' },
    { code: 'KeyJ', label: 'J' },
    { code: 'KeyK', label: 'K' },
    { code: 'KeyL', label: 'L' },
    { code: 'Semicolon', label: '; :' },
    { code: 'Quote', label: "' \"" },
    { code: 'Enter', label: 'Enter', width: 2.25 },
    { code: 'spacer', label: '', width: 3.5 },
  ],
  // ZXCV Row
  [
    { code: 'ShiftLeft', label: 'Shift', width: 2.25 },
    { code: 'KeyZ', label: 'Z' },
    { code: 'KeyX', label: 'X' },
    { code: 'KeyC', label: 'C' },
    { code: 'KeyV', label: 'V' },
    { code: 'KeyB', label: 'B' },
    { code: 'KeyN', label: 'N' },
    { code: 'KeyM', label: 'M' },
    { code: 'Comma', label: ', <' },
    { code: 'Period', label: '. >' },
    { code: 'Slash', label: '/ ?' },
    { code: 'ShiftRight', label: 'Shift', width: 2.75 },
    { code: 'spacer', label: '', width: 1.25 },
    { code: 'ArrowUp', label: '↑' },
    { code: 'spacer', label: '', width: 1.25 },
  ],
  // Bottom Row
  [
    { code: 'ControlLeft', label: 'Ctrl', macLabel: '⌃' },
    { code: 'MetaLeft', label: 'Win', macLabel: '⌘', width: 1.25 },
    { code: 'AltLeft', label: 'Alt', macLabel: '⌥', width: 1.25 },
    { code: 'Space', label: 'Space', width: 6.25 },
    { code: 'AltRight', label: 'Alt', macLabel: '⌥', width: 1.25 },
    { code: 'MetaRight', label: 'Win', macLabel: '⌘', width: 1.25 },
    { code: 'ContextMenu', label: 'Menu', width: 1.25 },
    { code: 'ControlRight', label: 'Ctrl', macLabel: '⌃' },
    { code: 'spacer', label: '', width: 0.25 },
    { code: 'ArrowLeft', label: '←' },
    { code: 'ArrowDown', label: '↓' },
    { code: 'ArrowRight', label: '→' },
  ]
];
